- name: To update
  apt:
    update_cache: yes

- name: install datadog
  shell: DD_AGENT_MAJOR_VERSION=7 DD_API_KEY="{{ key }}" DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"


- name: Start datadog
  systemd:
    name: datadog-agent
    state: restarted
    enabled: yes